using System.ComponentModel.DataAnnotations;
using System.Xml;

namespace DanskLogistikAPI.Models
{
    /// <summary>
    /// A snippet of SVG, used to generate the map
    /// They will generally include a minimal setup (likely generated by inkscape) but this will generally be ignored
    /// 
    /// This thing is equal to its own DTO, hence no DTO is defined
    /// </summary>
    public class SVGSnippet
    {
        /// <summary>
        /// Principal key
        /// </summary>
        [Key] public int Id { get; set; }

        /// <summary>
        /// Name of object for searching, this should also be the id attribute of the Node containing the actual display data
        /// </summary>
        public string Name { get; set; }

        public string Content {get; set;}
    }
}
